#pragma once

#define CPU_LOCAL_X86_APPLY_GS(VAR) (*((typeof(VAR) __seg_gs*)(&VAR)))

// on x86-64 all CPU local access is one operation so no special casing is needed
// for the fixed region of CPU local
#define CPU_LOCAL_FIXED_READ8(VAR)  CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_FIXED_READ16(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_FIXED_READ32(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_FIXED_READ64(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_FIXED_WRITE8(VAR, VAL)  (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_FIXED_WRITE16(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_FIXED_WRITE32(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_FIXED_WRITE64(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))

#define CPU_LOCAL_READ8(VAR)  CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_READ16(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_READ32(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_READ64(VAR) CPU_LOCAL_X86_APPLY_GS(VAR)
#define CPU_LOCAL_WRITE8(VAR, VAL)  (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_WRITE16(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_WRITE32(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))
#define CPU_LOCAL_WRITE64(VAR, VAL) (CPU_LOCAL_X86_APPLY_GS(VAR) = (VAL))

#define SET_CPU_LOCAL(v) asm volatile("wrmsr" : : "a"((uint64_t)(v) & 0xFFFFFFFF), "d"((uint64_t)(v) >> 32), "c"(0xC0000101) : "memory");
