#!/bin/sh

name=xorriso
version=1.5.8.pl02
revision=2
tarball_url="https://mirrors.ocf.berkeley.edu/gnu/xorriso/xorriso-${version}.tar.gz"
tarball_blake2b="3e15af0ec6082c590c6f13454783c277ff5439e7457e1ef90143f5406c71e6afbadc74b6765b5d5d833541171fec6b164376068b8ca44d0de298ec9ef420b4e2"
imagedeps="musl-tools"

configure() {
    mkdir -p build
    cd build
    CC="musl-gcc" LDFLAGS="-static"                                             \
    CPPFLAGS="-idirafter /usr/include -idirafter /usr/include/x86_64-linux-gnu" \
    "${source_dir}"/configure --prefix="${prefix}" --disable-shared --enable-static
}


build() {
    cd build
    make -j"$(nproc)" LDFLAGS="-all-static"
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install
    find "${dest_dir}/usr/local/bin" -maxdepth 1 -type f -exec strip {} + || true
}
