#! /bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.
cd "$srcdir"

depsdir="$srcdir/deps"
mkdir -p "$depsdir"

clone_repo_commit() {
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

clone_repo_commit                                       \
    https://codeberg.org/Mintsuki/Flanterm.git          \
    "$depsdir/flanterm"                                 \
    b5038e828de1dc6c049222a3c1670f7976e6c5a3

clone_repo_commit                                       \
    https://codeberg.org/Limine/limine-protocol.git     \
    "$depsdir/limine-protocol"                          \
    c5a7f597afa5da2b45f1edb1fd8f22c5ac6c57a7

clone_repo_commit                                       \
    https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
    "$depsdir/freestnd-c-hdrs"                          \
    097259a899d30f0a4b7a694de2de5fdda942e923

clone_repo_commit                                       \
    https://codeberg.org/OSDev/cc-runtime.git           \
    "$depsdir/cc-runtime"                               \
    dae79833b57a01b9fd3e359ee31def69f5ae899b
