#!/bin/sh

name=ovmf2-bin
version=20260821T130731Z
revision=1
tarball_url="https://github.com/osdev0/edk2-ovmf-stable-bins/releases/download/${version}/edk2-ovmf-bins.tar.xz"
tarball_blake2b="38ec1b202f2c809f6a8ad951a812ecc56df8583c4a209bcfc17fa143cbc256fd6b9976e013ff2a9d2c0ff84518b711b0b4d1e3eba34f98092b644813965eec18"

build() {
    :
}

package() {
    cp "${source_dir}"/ovmf-code-ia32.fd ${dest_dir}
    cp "${source_dir}"/ovmf-vars-ia32.fd ${dest_dir}
    cp "${source_dir}"/ovmf-code-x86_64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-vars-x86_64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-code-riscv64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-vars-riscv64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-code-aarch64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-vars-aarch64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-code-loongarch64.fd ${dest_dir}
    cp "${source_dir}"/ovmf-vars-loongarch64.fd ${dest_dir}
}
