#!/bin/sh

name=limine
version=12.7.0
revision=1
tarball_url="https://github.com/Limine-Bootloader/Limine/releases/download/v${version}/limine-${version}.tar.xz"
tarball_blake2b="3d057a782b07548e298f0bf40c7f1b123bd6c066d999aee55992b73ecf8b67f487e4f7dbe5ee374d0fa3de94c8a6b981e025de301488263901ff8544940d88c3"
imagedeps="clang llvm lld mtools nasm"

configure() {
    mkdir -p build
    cd build
    LDFLAGS="-static" CFLAGS_FOR_TARGET="-O2 -pipe" "${source_dir}"/configure --enable-all --prefix="${prefix}"
}

build() {
    cd build
    make -j"$(nproc)"
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install
    find "${dest_dir}/usr/local/bin" -maxdepth 1 -type f -exec strip {} + || true
}
