#!/bin/sh

name=limine
version=12.6.0
revision=1
tarball_url="https://github.com/Limine-Bootloader/Limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="d4ec93fbb8dd5d4ce073744582b220697ea9840b30655c5be0853685d26cd209e4789b6183492716e5253283244cf53ce6bcfe91753809eb66a7f4b8eb61502c"
imagedeps="clang llvm lld mtools nasm"

configure() {
    mkdir -p build
    cd build
    CFLAGS_FOR_TARGET="-O2 -pipe" "${source_dir}"/configure --enable-all --prefix="${prefix}"
}

build() {
    cd build
    make -j"$(nproc)"
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install
    find "${dest_dir}/usr/local/bin" -maxdepth 1 -type f -exec strip {} + || true
}
